.headers ON 
.mode column
PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS SIZE;
DROP TABLE IF EXISTS COLOUR;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS GENDER;
DROP TABLE IF EXISTS LISTINGS;

CREATE TABLE BRAND(
    IdBrand INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Brand_Name TEXT  NOT NULL
);
CREATE TABLE SIZE(
    IdSize INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Size TEXT  NOT NULL
);
CREATE TABLE COLOUR(
    IdColour INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Colour TEXT  NOT NULL
);
CREATE TABLE STATE(
    IdState INTEGER PRIMARY KEY UNIQUE NOT NULL,
    State TEXT  NOT NULL
);
CREATE TABLE GENDER(
    IdGender INTEGER PRIMARY KEY UNIQUE NOT NULL,
    GENDER TEXT  NOT NULL
);
CREATE TABLE LISTINGS(
    IdListing INTEGER PRIMARY KEY UNIQUE NOT NULL,
    IdBrand INTEGER NOT NULL,
    IdSize INTEGER NOT NULL,
    IdColour INTEGER NOT NULL,
    IdState INTEGER NOT NULL,
    IdGender INTEGER NOT NULL,
    FOREIGN KEY (IdBrand) REFERENCES Brand(IdBrand) ON UPDATE CASCADE,
    FOREIGN KEY (IdSize) REFERENCES Size(IdSize) ON UPDATE CASCADE,
    FOREIGN KEY (IdColour) REFERENCES Colour(IdColour) ON UPDATE CASCADE,
    FOREIGN KEY (IdState) REFERENCES State(IdState) ON UPDATE CASCADE,
    FOREIGN KEY (IdGender) REFERENCES Gender(IdGender) ON UPDATE CASCADE
)