.headers ON 
.mode column
PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS SIZE;
DROP TABLE IF EXISTS COLOUR;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS GENDER;
DROP TABLE IF EXISTS LISTINGS;
DROP TABLE IF EXISTS WISHLIST;
DROP TABLE IF EXISTS SHOPINGCART;

CREATE TABLE BRAND(
    IdBrand INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Brand TEXT  NOT NULL
);
CREATE TABLE SIZE(
    IdSize INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Size TEXT  NOT NULL
);
CREATE TABLE COLOUR(
    IdColour INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Colour TEXT  NOT NULL
);
CREATE TABLE STATE(
    IdState INTEGER PRIMARY KEY UNIQUE NOT NULL,
    State TEXT  NOT NULL
);
CREATE TABLE GENDER(
    IdGender INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Gender TEXT  NOT NULL
);
CREATE TABLE TYPE(
    IdType INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Type TEXT  NOT NULL
);

CREATE TABLE USER(
    IdUser INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL,
    User TEXT NOT NULL UNIQUE,
    PassWord TEXT NOT NULL,
    Name TEXT NOT NULL,
    SurName TEXT NOT NULL,
    Description TEXT,
    img BLOB ,
    Admin TEXT CHECK (Admin IN ('true', 'false') )
);

CREATE TABLE LISTINGS(
    IdListing INTEGER PRIMARY KEY UNIQUE NOT NULL,
    IdBrand INTEGER NOT NULL,
    IdSize INTEGER NOT NULL,
    IdColour INTEGER NOT NULL,
    IdState INTEGER NOT NULL,
    IdGender INTEGER NOT NULL,
    IdType INTEGER NOT NULL,
    IdUser INTEGER NOT NULL,
    img BLOB NOT NULL,
    Name TEXT NOT NULL,
    Price FLOAT NOT NULL,
    FOREIGN KEY (IdBrand) REFERENCES BRAND(IdBrand) ON UPDATE CASCADE,
    FOREIGN KEY (IdSize) REFERENCES SIZE(IdSize) ON UPDATE CASCADE,
    FOREIGN KEY (IdColour) REFERENCES COLOUR(IdColour) ON UPDATE CASCADE,
    FOREIGN KEY (IdState) REFERENCES STATE(IdState) ON UPDATE CASCADE,
    FOREIGN KEY (IdGender) REFERENCES GENDER(IdGender) ON UPDATE CASCADE,
    FOREIGN KEY (IdType) REFERENCES TYPE(IdType) ON UPDATE CASCADE,
    FOREIGN KEY (IdUser) REFERENCES USER(IdUser) ON UPDATE CASCADE
);
CREATE TABLE WISHLIST(
    IdUser Integer NOT NULL,
    IdListing INTEGER NOT NULL,
    PRIMARY KEY (IdUser, IdListing),
    FOREIGN KEY (IdListing) REFERENCES LISTINGS(IdListing) ON UPDATE CASCADE,
    FOREIGN KEY (IdUser) REFERENCES USER(IdUser) ON UPDATE CASCADE
);
CREATE TABLE SHOPPINGCART(
    IdUser Integer ,
    IdListing INTEGER NOT NULL,
    PRIMARY KEY (IdUser, IdListing),
    FOREIGN KEY (IdListing) REFERENCES LISTINGS(IdListing) ON UPDATE CASCADE,
    FOREIGN KEY (IdUser) REFERENCES USER(IdUser) ON UPDATE CASCADE
);