.headers ON 
.mode column
PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS WISHLIST;
DROP TABLE IF EXISTS SHOPINGCART;
CREATE TABLE USER(
    IdUser INTEGER NOT NULL PRIMARY KEY UNIQUE,
    Email TEXT NOT NULL,
    User TEXT NOT NULL UNIQUE,
    IdShoppingCart Integer UNIQUE NOT NULL,
    PassWord TEXT NOT NULL,
    FOREIGN KEY (IdShoppingCart) REFERENCES SHOPPINGCART(IdShoppingCart) ON UPDATE CASCADE
);
CREATE TABLE WISHLIST(
    IdWishList Integer PRIMARY KEY UNIQUE NOT NULL,
    IdListing INTEGER UNIQUE NOT NULL,
    IdUser INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (IdListing) REFERENCES LISTINGS(IdListing) ON UPDATE CASCADE,
    FOREIGN KEY (IdUser) REFERENCES USER(IdUser) ON UPDATE CASCADE
);
CREATE TABLE SHOPPINGCART(
    IdShoppingCart Integer UNIQUE NOT NULL,
    IdListing INTEGER UNIQUE NOT NULL,
    PRIMARY KEY (IdShoppingCart, IdListing),
    FOREIGN KEY (IdListing) REFERENCES LISTINGS(IdListing) ON UPDATE CASCADE
);