.headers ON 
.mode column
PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS ACC;
DROP TABLE IF EXISTS WISHLIST;
DROP TABLE IF EXISTS SHOPINGCART;
CREATE TABLE ACC{
    IdAcc INTEGER NOT NULL PRIMARY KEY UNIQUE,
    Email TEXT NOT NULL,
    User TEXT NOT NULL UNIQUE,
    PassWord TEXT NOT NULL
}
CREATE TABLE WISHLIST{
    IdWishList Integer PRIMARY KEY UNIQUE NOT NULL,
    IdListing INTEGER UNIQUE NOT NULL,
    IdAcc INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (IdListing) REFERENCES LISTINGS(IdListing) ON UPDATE CASCADE,
    FOREIGN KEY (IdAcc) REFERENCES ACC(IdAcc) ON UPDATE CASCADE
}
CREATE TABLE SHOPINGCART{
    IdSopingCart Integer PRIMARY KEY UNIQUE NOT NULL,
    IdListing INTEGER UNIQUE NOT NULL,
    IdAcc INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (IdListing) REFERENCES LISTINGS(IdListing) ON UPDATE CASCADE,
    FOREIGN KEY (IdAcc) REFERENCES ACC(IdAcc) ON UPDATE CASCADE
}