<?php
    include_once("../templates/footer.php");
    include_once("../templates/header.php");
    include_once("../templates/listing.php");
?>
    <?php
        print_header();
        print_listings();
        print_footer()?>
</html>